### ISSUE TITLE
incompatible with pypy

### ISSUE THREAD

**Issue by marscher** [conda-forge/msmtools-feedstock#22]
The automatically generated PR to support pypy in #20 did not add pypy to the build matrix. I accidentally merged it, since I didn't spot the missing entries. Now the bot has created pypy support PRs for dependent projects like pyemma. I guess we should explicitly forbid pypy, since the Cython modules in msmtools are not compatible. The same should apply for bhmm, thermtools and pyemma. 

@clonker: should we spent effort on this or just close the pypy PRs for good? Eventually they will be re-created. I haven't checked the details.

**Comment by clonker** [comment]
under the assumptions that msmtools is probably going to go stale eventually I vote to just close the PRs and focus on the deeptime implementations

**Comment by marscher** [comment]
OK.
The skipping should already be in place, but is ignored or not properly implemented (related issue: https://github.com/conda-forge/pywps-feedstock/issues/14)

**Comment by clonker** [comment]
Alright, thanks!
